name: CI General Checks

on:
  pull_request:
    branches:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CheckIfTestsAreAdded:
    if: github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch develop branch
        run: git fetch origin develop:develop
      - name: Check for new tests
        run: |
          TEST_ADDITIONS=$(git diff develop | grep '^[+]' | grep -E 'it\(|test\(|describe\(')
          TEST_FILES=$(git diff develop --name-only | grep '.spec.ts$')
          if [[ -z "$TEST_ADDITIONS" ]] || [[ -z "$TEST_FILES" ]] ; then
            echo "Please, make sure your PR contains tests!"
            exit 1
          else
            echo "Thanks for implementing tests!"
          fi
  Test:
    runs-on: ubuntu-latest # runs a test on Ubuntu

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run test cases
        working-directory: ./
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm ci
          npm test
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
