name: CI/CD DEV

on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    branches: [ develop ]
    types: closed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  TestBuild:
    runs-on: ubuntu-latest # runs a test on Ubuntu
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run test cases
        working-directory: ./
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm ci
          npm test